-- ==========================================================================
-- Giraffe — بذور الأقسام
--
-- ⚠️  الملف ده **مولّد آلياً**. ممنوع تعديله يدوي.
--
--     المصدر: app/lib/data/catalog/categories.dart
--     المولّد: supabase/tools/gen_catalog_seed.py
--
-- 21 قسم رئيسي · 113 قسم فرعي
-- ==========================================================================

insert into public.categories
  (id, name_ar, name_en, icon, restricted, is_service, is_featured, sort_order)
values
  ('mobiles', 'موبايلات وتابلت', 'Mobiles & Tablets', 'smartphone_rounded', false, false, true, 0),
  ('computers', 'كمبيوتر ولابتوب', 'Computers & Laptops', 'laptop_mac_rounded', false, false, false, 10),
  ('electronics', 'إلكترونيات وأجهزة', 'Electronics', 'tv_rounded', false, false, true, 20),
  ('cameras', 'كاميرات وتصوير', 'Cameras & Photography', 'photo_camera_rounded', false, false, false, 30),
  ('gaming', 'ألعاب وأجهزة ألعاب', 'Gaming', 'sports_esports_rounded', false, false, true, 40),
  ('vehicles', 'سيارات ومركبات', 'Vehicles', 'directions_car_rounded', false, false, true, 50),
  ('furniture', 'أثاث ومفروشات', 'Furniture & Home', 'chair_rounded', false, false, true, 60),
  ('appliances', 'أجهزة منزلية', 'Home Appliances', 'kitchen_rounded', false, false, false, 70),
  ('fashion', 'أزياء وموضة', 'Fashion', 'checkroom_rounded', false, false, true, 80),
  ('watches', 'ساعات ومجوهرات', 'Watches & Jewellery', 'watch_rounded', false, false, true, 90),
  ('kids', 'مستلزمات أطفال', 'Kids & Babies', 'child_friendly_rounded', false, false, false, 100),
  ('sports', 'رياضة ولياقة', 'Sports & Fitness', 'fitness_center_rounded', false, false, false, 110),
  ('hobbies', 'هوايات وموسيقى', 'Hobbies & Music', 'piano_rounded', false, false, false, 120),
  ('books', 'كتب ومستلزمات دراسية', 'Books & Study', 'menu_book_rounded', false, false, false, 130),
  ('tools', 'عدد وأدوات', 'Tools & Equipment', 'handyman_rounded', false, false, false, 140),
  ('business', 'معدات محلات ومطاعم', 'Business Equipment', 'storefront_rounded', false, false, false, 150),
  ('construction', 'مواد بناء وديكور', 'Construction & Decor', 'foundation_rounded', true, false, false, 160),
  ('agriculture', 'زراعة ونباتات', 'Agriculture & Plants', 'local_florist_rounded', false, false, false, 170),
  ('pets', 'حيوانات ومستلزماتها', 'Pets & Supplies', 'pets_rounded', true, false, false, 180),
  ('services', 'خدمات مقابل خدمات', 'Skill for Skill', 'swap_horiz_rounded', false, true, true, 190),
  ('misc', 'متنوع', 'Everything Else', 'category_rounded', false, false, false, 200)
on conflict (id) do update set
  name_ar     = excluded.name_ar,
  name_en     = excluded.name_en,
  icon        = excluded.icon,
  restricted  = excluded.restricted,
  is_service  = excluded.is_service,
  is_featured = excluded.is_featured,
  sort_order  = excluded.sort_order;

insert into public.subcategories
  (id, category_id, name_ar, name_en, sort_order)
values
  ('mobiles.phones', 'mobiles', 'موبايلات', 'Mobile phones', 0),
  ('mobiles.tablets', 'mobiles', 'تابلت', 'Tablets', 10),
  ('mobiles.smartwatch', 'mobiles', 'ساعات ذكية', 'Smart watches', 20),
  ('mobiles.phoneacc', 'mobiles', 'إكسسوارات موبايل', 'Phone accessories', 30),
  ('mobiles.numbers', 'mobiles', 'أرقام مميزة', 'Premium numbers', 40),
  ('computers.laptops', 'computers', 'لابتوب', 'Laptops', 0),
  ('computers.desktops', 'computers', 'كمبيوتر مكتبي', 'Desktops', 10),
  ('computers.parts', 'computers', 'قطع ومكونات', 'Components', 20),
  ('computers.monitors', 'computers', 'شاشات', 'Monitors', 30),
  ('computers.printers', 'computers', 'طابعات', 'Printers', 40),
  ('computers.network', 'computers', 'شبكات وراوتر', 'Networking', 50),
  ('electronics.tv', 'electronics', 'تلفزيونات', 'TVs', 0),
  ('electronics.audio', 'electronics', 'صوتيات وسماعات', 'Audio & headphones', 10),
  ('electronics.projectors', 'electronics', 'بروجيكتور', 'Projectors', 20),
  ('electronics.drones', 'electronics', 'درون', 'Drones', 30),
  ('electronics.security', 'electronics', 'كاميرات مراقبة', 'Security cameras', 40),
  ('electronics.wearables', 'electronics', 'أجهزة قابلة للارتداء', 'Wearables', 50),
  ('cameras.dslr', 'cameras', 'كاميرات احترافية', 'DSLR & mirrorless', 0),
  ('cameras.lenses', 'cameras', 'عدسات', 'Lenses', 10),
  ('cameras.action', 'cameras', 'كاميرات أكشن', 'Action cameras', 20),
  ('cameras.lighting', 'cameras', 'إضاءة واستوديو', 'Lighting & studio', 30),
  ('cameras.tripods', 'cameras', 'حوامل ومثبتات', 'Tripods & gimbals', 40),
  ('gaming.consoles', 'gaming', 'أجهزة ألعاب', 'Consoles', 0),
  ('gaming.games', 'gaming', 'أشرطة وألعاب', 'Games', 10),
  ('gaming.gamingacc', 'gaming', 'إكسسوارات ألعاب', 'Gaming accessories', 20),
  ('gaming.vr', 'gaming', 'نظارات واقع افتراضي', 'VR headsets', 30),
  ('gaming.gamingpc', 'gaming', 'أجهزة ألعاب كمبيوتر', 'Gaming PCs', 40),
  ('vehicles.cars', 'vehicles', 'سيارات', 'Cars', 0),
  ('vehicles.motorcycles', 'vehicles', 'موتوسيكلات', 'Motorcycles', 10),
  ('vehicles.scooters', 'vehicles', 'سكوتر كهربائي', 'E-scooters', 20),
  ('vehicles.bicycles', 'vehicles', 'دراجات', 'Bicycles', 30),
  ('vehicles.spare', 'vehicles', 'قطع غيار', 'Spare parts', 40),
  ('vehicles.tires', 'vehicles', 'إطارات وجنوط', 'Tyres & rims', 50),
  ('vehicles.boats', 'vehicles', 'قوارب وجت سكي', 'Boats & jet skis', 60),
  ('vehicles.trucks', 'vehicles', 'شاحنات ومعدات ثقيلة', 'Trucks & heavy equipment', 70),
  ('furniture.living', 'furniture', 'أنتريهات وصالونات', 'Living room', 0),
  ('furniture.bedroom', 'furniture', 'غرف نوم', 'Bedroom', 10),
  ('furniture.dining', 'furniture', 'سفرة', 'Dining', 20),
  ('furniture.office', 'furniture', 'أثاث مكتبي', 'Office furniture', 30),
  ('furniture.decor', 'furniture', 'ديكور وتحف', 'Decor', 40),
  ('furniture.carpets', 'furniture', 'سجاد وستائر', 'Carpets & curtains', 50),
  ('furniture.outdoor', 'furniture', 'أثاث خارجي', 'Outdoor furniture', 60),
  ('appliances.fridges', 'appliances', 'ثلاجات وديب فريزر', 'Fridges & freezers', 0),
  ('appliances.washers', 'appliances', 'غسالات', 'Washing machines', 10),
  ('appliances.ac', 'appliances', 'تكييفات ومراوح', 'AC & fans', 20),
  ('appliances.cooking', 'appliances', 'أفران وبوتاجازات', 'Ovens & cookers', 30),
  ('appliances.small', 'appliances', 'أجهزة صغيرة', 'Small appliances', 40),
  ('appliances.water', 'appliances', 'سخانات وفلاتر مياه', 'Heaters & water filters', 50),
  ('fashion.menswear', 'fashion', 'ملابس رجالي', 'Men''s clothing', 0),
  ('fashion.womenswear', 'fashion', 'ملابس حريمي', 'Women''s clothing', 10),
  ('fashion.shoes', 'fashion', 'أحذية', 'Shoes', 20),
  ('fashion.bags', 'fashion', 'شنط', 'Bags', 30),
  ('fashion.perfumes', 'fashion', 'عطور', 'Perfumes', 40),
  ('fashion.accessories', 'fashion', 'إكسسوارات', 'Accessories', 50),
  ('fashion.abaya', 'fashion', 'عبايات وملابس تقليدية', 'Abayas & traditional', 60),
  ('watches.luxwatches', 'watches', 'ساعات فاخرة', 'Luxury watches', 0),
  ('watches.watches2', 'watches', 'ساعات', 'Watches', 10),
  ('watches.gold', 'watches', 'ذهب', 'Gold', 20),
  ('watches.silver', 'watches', 'فضة', 'Silver', 30),
  ('watches.gems', 'watches', 'أحجار كريمة', 'Gemstones', 40),
  ('kids.strollers', 'kids', 'عربيات أطفال', 'Strollers', 0),
  ('kids.carseats', 'kids', 'كراسي سيارة', 'Car seats', 10),
  ('kids.toys', 'kids', 'ألعاب أطفال', 'Toys', 20),
  ('kids.kidsclothes', 'kids', 'ملابس أطفال', 'Kids clothing', 30),
  ('kids.kidsfurniture', 'kids', 'أثاث أطفال', 'Kids furniture', 40),
  ('sports.gym', 'sports', 'أجهزة جيم', 'Gym equipment', 0),
  ('sports.weights', 'sports', 'أوزان', 'Weights', 10),
  ('sports.football', 'sports', 'كرة قدم', 'Football', 20),
  ('sports.camping', 'sports', 'تخييم ورحلات', 'Camping & outdoors', 30),
  ('sports.fishing', 'sports', 'صيد', 'Fishing', 40),
  ('sports.water', 'sports', 'رياضات مائية', 'Water sports', 50),
  ('hobbies.instruments', 'hobbies', 'آلات موسيقية', 'Musical instruments', 0),
  ('hobbies.collectibles', 'hobbies', 'مقتنيات وتحف', 'Collectibles', 10),
  ('hobbies.coins', 'hobbies', 'عملات وطوابع', 'Coins & stamps', 20),
  ('hobbies.art', 'hobbies', 'لوحات وفنون', 'Art', 30),
  ('hobbies.models', 'hobbies', 'مجسمات ومكعبات', 'Models & figures', 40),
  ('books.books2', 'books', 'كتب', 'Books', 0),
  ('books.textbooks', 'books', 'كتب دراسية', 'Textbooks', 10),
  ('books.stationery', 'books', 'أدوات مكتبية', 'Stationery', 20),
  ('books.ereaders', 'books', 'أجهزة قراءة', 'E-readers', 30),
  ('tools.power', 'tools', 'عدد كهربائية', 'Power tools', 0),
  ('tools.hand', 'tools', 'عدد يدوية', 'Hand tools', 10),
  ('tools.generators', 'tools', 'مولدات', 'Generators', 20),
  ('tools.welding', 'tools', 'لحام', 'Welding', 30),
  ('tools.measuring', 'tools', 'أجهزة قياس', 'Measuring tools', 40),
  ('business.restaurant', 'business', 'معدات مطاعم', 'Restaurant equipment', 0),
  ('business.displays', 'business', 'فاترينات ورفوف', 'Displays & shelving', 10),
  ('business.pos', 'business', 'أنظمة كاشير', 'POS systems', 20),
  ('business.salon', 'business', 'معدات صالونات', 'Salon equipment', 30),
  ('business.medical', 'business', 'أجهزة عيادات', 'Clinic equipment', 40),
  ('construction.tiles', 'construction', 'سيراميك ورخام', 'Tiles & marble', 0),
  ('construction.doors', 'construction', 'أبواب وشبابيك', 'Doors & windows', 10),
  ('construction.paint', 'construction', 'دهانات', 'Paint', 20),
  ('construction.sanitary', 'construction', 'أدوات صحية', 'Sanitary ware', 30),
  ('construction.lighting2', 'construction', 'إضاءة', 'Lighting', 40),
  ('agriculture.plants', 'agriculture', 'نباتات', 'Plants', 0),
  ('agriculture.seeds', 'agriculture', 'بذور وشتلات', 'Seeds & seedlings', 10),
  ('agriculture.farmtools', 'agriculture', 'أدوات زراعية', 'Farm tools', 20),
  ('agriculture.irrigation', 'agriculture', 'أنظمة ري', 'Irrigation', 30),
  ('pets.petsupplies', 'pets', 'مستلزمات حيوانات', 'Pet supplies', 0),
  ('pets.aquarium', 'pets', 'أحواض أسماك', 'Aquariums', 10),
  ('pets.cages', 'pets', 'أقفاص وبيوت', 'Cages & houses', 20),
  ('pets.birds', 'pets', 'طيور زينة', 'Ornamental birds', 30),
  ('services.design', 'services', 'تصميم وجرافيك', 'Design & graphics', 0),
  ('services.dev', 'services', 'برمجة ومواقع', 'Development & web', 10),
  ('services.photo', 'services', 'تصوير ومونتاج', 'Photo & video', 20),
  ('services.teaching', 'services', 'دروس وتدريس', 'Tutoring', 30),
  ('services.translation', 'services', 'ترجمة وكتابة', 'Translation & writing', 40),
  ('services.repair', 'services', 'صيانة وإصلاح', 'Repair & maintenance', 50),
  ('services.marketing', 'services', 'تسويق وسوشيال', 'Marketing & social', 60),
  ('services.fitness', 'services', 'تدريب رياضي', 'Fitness training', 70),
  ('services.events', 'services', 'تنظيم مناسبات', 'Events', 80),
  ('misc.other', 'misc', 'أخرى', 'Other', 0)
on conflict (id) do update set
  category_id = excluded.category_id,
  name_ar     = excluded.name_ar,
  name_en     = excluded.name_en,
  sort_order  = excluded.sort_order;
